# Generated by Django 5.0.6 on 2024-05-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicle_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
